config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :classifieds
  devise_for :users, controllers: { registrations: "registrations", :omniauth_callbacks => "omniauth_callbacks"  }, path_names: { sign_up: ''}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#home'
  
   %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'my-profile', to: 'profiles#profileoverview'

  get 'dashboard', to: 'dashboard#index'

  get 'signup', to: 'pages#signup'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
    get 'logout', to: 'devise/sessions#destroy'
  end

  get 'search', to: 'search#search'
  get 'search/autocomplete', to: 'search#autocomplete'

  post 'classifieds/product/confirm', to: 'classifieds#confirmPurchase'

  get 'users/upgrade', to: 'subscription#upgrade'
  get 'users/subscribe/confirm', to: 'subscription#confirm'
  get 'users/subscribe/success', to: 'subscription#success'
  get 'users/subscribe/error', to: 'subscription#error'
  post 'users/subscribe/', to: 'subscription#subscribe'
  post 'classifieds/payment/confirmation/:id', to: 'classifieds#stripeProcess'
  get 'classifieds/addons/confirm', to: 'classifieds#addonConfirm'
  get 'profile/gallery', to: 'profiles#galleryOverview'
  get 'invoices', to: 'classifieds#soldInvoices'
  get 'invoices/view/:id', to: 'classifieds#viewInvoice'
  put 'invoices/refund/:id', to: 'classifieds#processRefund'
  get 'purchase/:id/thankyou', to: 'classifieds#thankyou'

  post 'classifieds/:id/addons', to: 'classifieds#processAddon'
  get 'update_cats', to: 'classifieds#update_cats',  :defaults => { :format => 'json' }
  get 'ebaygetitem', to: 'classifieds#getebayitem',  :defaults => { :format => 'json' }
  get 'gbgetitem', to: 'classifieds#getgbitem',  :defaults => { :format => 'json' }
  get 'changeArchive', to: 'classifieds#changeArchive', :defaults => { :format => 'json' }
  get 'smartSearch', to: 'search#ajaxSearch', :defaults => { :format => 'json' }
  post 'submithelp', to: 'application#create_groove_ticket', :defaults => { :format => 'json' }
  post 'addonCreditsProcess', to: 'classifieds#processAddonCredits'
  post 'getBlogPosts', to: 'pages#getBlogPost',  :defaults => { :format => 'json' }
  get 'profile/:userid/gallery/:imgid/delete', to: 'profiles#galleryImageDelete', :defaults => {:format => 'json'}
  post 'profile/:id/gallery/new', to: 'profiles#galleryImageUpload', :defaults => {:format => 'json'}
  delete 'classifieds/:id/images/:imgid', to: 'classifieds#extraImageDelete', :defaults => {:format => 'json'}
  post 'profile/:id/status', to: 'profiles#createNewStatus', :defaults => {:format => 'json'}
  delete 'profile/status/:statusid', to: 'profiles#deleteStatus', :defaults => {:format => 'json'}
  post 'users/:userid/subscribe/cardchange',  to: 'subscription#cardChange', :defaults => {:format => 'json'}
  post 'profiles/:id/contact', to: 'profiles#emailContact', :defaults => {:format => 'json'}

end

app/models/profile.rb
require 'elasticsearch/model'

class Profile < ActiveRecord::Base

	before_create :randomize_id

	paginates_per 20

	max_paginates_per 20
	
	belongs_to :user

	has_many :proserv, :dependent => :destroy
	has_many :services, through: :proserv

	has_many :profilebrand, :dependent => :destroy
	has_many :brand, through: :profilebrand

	has_one :plans, primary_key: :level, foreign_key: :id

	has_one :profilestatus

	serialize :times, JSON

	geocoded_by :postcode
	after_validation :geocode, if: ->(obj){ obj.postcode.present? and obj.postcode_changed? }

	after_save :reindex
	after_destroy :reindex

	searchkick locations: ["location"], callbacks: false, suggest: [:name, :golfclub], highlight: [:name, :golfclub, :bio], word_start: [:name, :bio, :golfclub], boost_where: {featured: {value: 1, factor: 100}}, match: :word_start, searchable: [:name, :bio, :golfclub, :brand]

	def search_data
		attributes.merge(services: services.map(&:servtitle), location: {lat: self.latitude, lon: self.longitude}, brandname: brand.map(&:brandname))
	end

	def after_save()
		Profile.reindex
    	return id = self.id
  	end

    private
      def randomize_id
        begin
          self.id = SecureRandom.random_number(1_000_000)
        end while Profile.where(id: self.id).exists?
      end	
	
	#Profile.reindex

end

app/controllers/profiles_controller.rb
class ProfilesController < InheritedResources::Base
	before_filter :sanitize_page_params

	before_action :authenticate_user!, except: [:show, :emailContact]
	before_action :set_user, only: [:edit, :update, :profileoverview, :galleryOverview, :galleryImageDelete, :galleryImageUpload, :deleteStatus, :createNewStatus]
	before_action :authorize_user, except: [:index, :show, :profileoverview, :galleryOverview, :galleryImageDelete, :galleryImageUpload, :deleteStatus, :createNewStatus, :emailContact]

	def index

	end

	def new
	    @profiles = current_user.profile.build
	end

	def create
	    @profiles = current_user.profile.build
	end

	def show
		@profile = Profile.find_by id: params[:id]
		@avatar = Avatars.where(user_id: @profile.user.id, protype: 'avatar').take
		@images = Progallery.where(user_id: @profile.user.id, protype: 'progallery').order("created_at DESC")
		@ads = Classifieds.where(user_id: @profile.user.id, status: 1).order("created_at DESC").page(params[:page]).per(10)


		event = Analytic.new
		event.analytic_type = 1
		if !cookies[:profileAnalytics]
			event.identifier = SecureRandom.hex
			cookies[:profileAnalytics] = event.identifier
		else
			event.identifier = cookies[:profileAnalytics]
		end
		event.profiles_id = params[:id]
		event.classifieds_id = 0
		if session[:searchQuery]
			event.properties = Hash.new
			event.properties[:searchQuery] = session[:searchQuery]
		end
		# = {test: '123'}
		event.save
	end

	def edit
	   	@profiles = @profile
		@avatar = Avatars.where(user_id: current_user.id, protype: 'avatar').take
		@brands = Brand.all
		@services = Services.all
	   	@attributes = Profile.attribute_names - %w(id user_id created_at updated_at)
	end

	def update

		params[:profile][:bio]= ActionController::Base.helpers.sanitize(params[:profile][:bio], tags: %w(strong em ul li p br i u))

		profile = @profile.update(profile_params)
		profile = current_user.profile
		profile.times = params[:profile][:times]

		if profile.wizard == 1
			redirectdash = true
		else
			redirectdash = false
		end

		profile.wizard = 0
		profile.save
		profile = current_user.profile

		if !params[:profiles][:theimage].blank?
			@images = Avatars.where(user_id: current_user.id, protype: 'avatar').delete_all
			image = Avatars.new()
			image.user_id = current_user.id
			image.theimage = params[:profiles][:theimage]
			image.protype = 'avatar'
			if image.save
			   	checking = true
			else
			    checking = false
			end
		end	
		if !params[:profiles][:brands].blank?
			probrands = Profilebrand.where('profile_id': profile.id).delete_all

			params[:profiles][:brands].each do |brand|
				probrand = Profilebrand.new()
				probrand.profile_id = profile.id
				probrand.brand_id = brand
				if probrand.save
					@checking = true
				else
					@checking = false
				end
			end			
		end
		if !params[:service].blank?
			proservs = Proserv.where('profile_id': profile.id).delete_all

			params[:service].each do |serv|
				newproserv = Proserv.new()
				newproserv.profile_id = profile.id
				newproserv.services_id = serv[0]
				if newproserv.save
					@checking = true
				else
					@checking = false
				end
			end
		end

		if defined?(redirectdash)
			redirect_to dashboard_path(tour: "true"), tour: "true", notice: 'Your profile was successfully updated.'
		else
			redirect_to my_profile_path, notice: 'Your profile was successfully updated.'
		end

		#respond_to do |format|
	      #if @profiles.update(profile_params)
	        #format.html { redirect_to @profiles, notice: 'Your profile was successfully updated 2.' }
	        #format.json { render :show, status: :updated, location: @profiles }
	      #else
	        #format.html { render :new }
	        #format.json { render json: @profiles.errors, status: :unprocessable_entity }
	      #end
	    #end
	end

	def profileoverview
		@avatar = Avatars.where(user_id: current_user.id, protype: 'avatar').take
	   	@attributes = Profile.attribute_names - %w(id user_id created_at updated_at)
	end

	def galleryOverview
		@images = Progallery.where(user_id: @profiles.id, protype: 'progallery').order("created_at DESC")
		@limit = @profile.plans.photos <= @images.size ? true : false
	end

	def galleryImageUpload
		images = Progallery.where(user_id: params[:id], protype: 'progallery')
		@limit = @profile.plans.photos <= images.size ? true : false

		if !@limit
			if params[:croppedImage].try(:original_filename) == 'blob'
			  params[:croppedImage].original_filename << '.png'
			end
			image = Progallery.new(theimage: params[:croppedImage])
			image.user_id = params[:id]
			image.protype = 'progallery'
			if image.save
				render json: {status: true}
			else
				render json: {status: false, error: true}
			end 
		else
			render json: {status: false, error: true}
		end
	end

	def galleryImageDelete
		if Progallery.find(params[:imgid]).destroy
			render json: {status: true}
		else
			render json: {status: false, error: true}
		end

	end

	def createNewStatus
		puts params.inspect
		check = Profilestatus.where(profile_id: params[:id])
		puts check.inspect
		if !check.blank?
			check.destroy_all
		end
		status = Profilestatus.new(profile_id: params[:id], status: params[:status])
		if status.save
			render json: {status: true, data: status.to_json}
		else
			render json: {status: false, error: true}
		end
	end

	def deleteStatus
		if Profilestatus.find(params[:statusid]).destroy
			render json: {status: true}
		else
			render json: {status: false, error: true}
		end
	end

	def emailContact
		pro = Profile.find_by user_id: params[:id].to_i
		mailSent = Transactionals.pro_contact(pro.user.email, pro.name, params[:user], params[:subject], params[:themessage]).deliver_now
		if mailSent
			render json: {status: true}
		else
			render json: {status: false, error: true}
		end
	end

	private

		def sanitize_page_params
	    	params[:id] = params[:id].to_i
	  	end

	    def set_user
	      	@profiles = @profile
	    end

	    def authorize_user
	      	redirect_to my_profile_path, notice: "This is not the profile you're looking for..." if current_user.profile.id != params[:id]
	    end

		def profile_params
	  		params.require(:profile).permit(:latitude, :longitude, :postcode, :name, :bio, :golfclub, :phone, :position, :fb, :twitter, :youtube, :times)
		end

		def status_params
			params.require(:profilestatus).permit(:user_id, :description)
		end
end

app/helpers/profiles_helper.rb
module ProfilesHelper

end

app/views/profiles/edit.html.erb
<div class="wrapper wrapper-content container animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    <h2>
                        Edit Your Profile
                    </h2>
                    <p>
                        Use for the fields below to help put your profile together. <strong>NOTE:</strong> Any changes made and saved will be applied to your live profile immediately.
                    </p>
                    <%= render 'form' %>
                </div>
            </div>
        </div>

    </div>
</div>

app/views/profiles/galleryOverview.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>Profile Image Gallery</h2>
        <ol class="breadcrumb">
            <li>
                <%= link_to "Dashboard", dashboard_path %>
            </li>
            <li>
                <%= link_to "My Profile", my_profile_path %>
            </li>
            <li class="active">
                <strong>Profile Image Gallery</strong>
            </li>
        </ol>
    </div>
</div>
 
<div class="lightBoxGallery">
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <div class="file-manager">
                            <% if !@limit %>
                                <button class="btn btn-primary btn-block" data-toggle="modal" data-target="#imageUpload">Upload Files</button>
                            <% else %>
                                <span class="showtooltip" data-toggle="tooltip" data-placement="top" title="You have reached your extra image limit. Please upgrade your account to make more.">
                                    <button class="btn btn-primary btn-block disabled">Upload Files</button>
                                </span>
                            <% end %>
                            <div class="hr-line-dashed"></div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 animated fadeInRight">
                <div class="row">
                    <div class="col-lg-12">
                        <% if !@images.nil? %>
                            <% @images.each do |file| %>
                                <div class="file-box col-lg-4">
                                    <div class="file">
                                        <div class="actions"><a href="<%= file.theimage.url %>" class="btn btn-primary" data-gallery=""><i class="fa fa-eye"></i></a>&nbsp;<a class="btn btn-primary delete" data-userid="<%= @profile.id%>" data-imgid="<%= file.id %>"><i class="fa fa-trash"></i></a></div>
                                        <span class="corner"></span>

                                        <div class="icon">
                                            <img alt="image" class="img-responsive" src="<%= file.theimage.url %>">
                                        </div>
                                        <div class="file-name">
                                            <%= File.basename(file.theimage.path) %>
                                            <br />
                                            <small><% file.created_at %></small>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                        <% else %>
                            <h3>No Images yet. <a href="#" class="btn btn-primary">Upload Image</a></h3>
                        <% end %>

                    </div>
                </div>
            </div>  
        </div>
    </div>
    <div id="blueimp-gallery" class="blueimp-gallery">
        <div class="slides"></div>
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
    </div>
</div>

<div class="modal inmodal fade" id="imageUpload" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form id="feedback_form" novalidate="novalidate" accept-charset="UTF-8">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Image Upload</h4>
                    <small class="font-bold">Upload an Image from your computer</small>
                </div>
                <div class="modal-body">
                    <div id="loadingImg" class="loading hide">
                       <div class="progress">
                          <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                          </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group">
                              <div class="image-crop">
                                <div class="img-container">
                                    <%= image_tag "placeholder.png", :id => 'image'  %>
                                </div>
                              </div> 
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div>                  
                              <div class="btn-group">
                                <label title="Upload image file" for="gallery_upload_image" class="btn btn-primary">
                                    <input type="file" accept="image/*" name="cropimage" id="gallery_upload_image" class="hide">
                                    Upload new image
                                </label>
                              </div>
                              <h4>Control Options</h4>
                              <div class="btn-group col-lg-12">
                                  <button class="btn btn-white col-lg-6" id="zoomIn" type="button">Zoom In</button>
                                  <button class="btn btn-white col-lg-6" id="zoomOut" type="button">Zoom Out</button>
                                  <button class="btn btn-white col-lg-6" id="rotateLeft" type="button">Rotate Left</button>
                                  <button class="btn btn-white col-lg-6" id="rotateRight" type="button">Rotate Right</button>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>  

                <div class="modal-footer">
                    <button type="cancel" class="btn btn-white" data-dismiss="modal">Close</button>
                    <button type="submit" data-id="<%= @profile.id%>" id="uploadButton" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/profile.html.erb
profile edit screen

app/views/profiles/profileoverview.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Profile Overview</h2>
        <ol class="breadcrumb">
            <li>
                <p>This is a preview overview of your public profile</p>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row animated fadeInRight">
      <div class="col-md-4">
          <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h5>Profile Details <span class="showtooltip" data-toggle="tooltip" data-placement="top" title="The basic details about you as your golf club's pro."><i class="fa fa-question-circle"></i></span></h5>
              </div>
              <div>
                  <div class="ibox-content no-padding border-left-right">
                      <img alt="image" class="img-responsive" src="<%= image_path(@avatar.theimage) if !@avatar.theimage.blank? %>">
                  </div>
                  <div class="ibox-content profile-content">
                      <h4><strong><%= @profile.name %></strong></h4>
                      <h5><%= @profile.golfclub %></h5>
                      <% latLon = "#{@profile.latitude}, #{@profile.longitude}" %>
                      <p><i class="fa fa-map-marker"></i> <%= Geocoder.search(latLon).first.city if !Geocoder.search(latLon).first.nil? %>, <%= Geocoder.search(latLon).first.sub_state if !Geocoder.search(latLon).first.nil? %></p>
                      <div id='showClub' style="height:200px; width:100%;"></div>
                      <hr/>
                      <div class="manufactors clearfix">
                        <h4>Manufacturers We Stock:</h4>
                        <ul class="col-xs-12 clearfix">
                          <% @profile.brand.each do |brand| %>
                            <li class="sm-6"><%= brand.brandname %></li>
                          <% end %>
                        </ul>
                      </div>
                      <div class="user-button">
                          <div class="row">
                              <div class="col-md-12">
                                  <a href="/profiles/<%= @profile.id %>/edit" type="button" class="btn btn-primary btn-md col-lg-5"><i class="fa fa-edit"></i> Edit Profile</a>
                                  <a href="/profiles/<%= @profile.id %>" type="button" class="btn btn-primary btn-md col-lg-5 pull-right"><i class="fa fa-user"></i> View Profile</a>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
      <div class="col-md-8">
          <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h5>Latest Status Post <span class="showtooltip" data-toggle="tooltip" data-placement="top" title="Let your potential customers know thw latest news in small twitter-like status updates."><i class="fa fa-question-circle"></i></span></h5>
              </div>
              <div class="ibox-content">

                  <div>
                      <div class="feed-activity-list" id="status-list">
                          <% if !@profile.profilestatus.blank? %>
                            <div class="status" id="status-<%= @profile.profilestatus.id %>"><p  class="col-sm-10"><%= @profile.profilestatus.status %></p><a href="#" id="deleteStatus" data-id="<%= @profile.profilestatus.id %>" onclick="return false" class="col-sm-1 pull-right btn btn-danger danger"><i class="fa fa-trash"></i></a></div>
                          <% else %>
                            <p><strong>You have not posted a status update yet. <a href="#" onclick="return false" class="btn btn-primary" data-toggle="modal" data-target="#statusUpdate">Post New Status</a></strong></p>
                          <% end %>
                      </div>
                      <a href="#" onclick="return false" class="btn btn-primary" data-toggle="modal" data-target="#statusUpdate">Post New Status</a>
                  </div>

              </div>
          </div>

          <div class="ibox float-e-margins">
            <div class="ibox-title">
                  <h5>About Me</h5>
              </div>
             <div class="ibox-content">
                    <div class="row services-list">
                        <ul>
                          <% @profile.services.each do |service| %>
                            <li class="col-sm-4 <%= service.servtitle.parameterize %>">
                              <%= '<i class="fa fa-shopping-cart"></i>'.html_safe if service.servtitle.parameterize == "pro-retail-shop" %>
                              <%= '<i class="fa fa-dot-circle-o"></i>'.html_safe if service.servtitle.parameterize == "driving-range" %>
                              <%= '<i class="fa fa-cutlery"></i>'.html_safe if service.servtitle.parameterize == "restaurant-bar" %>
                              <%= '<i class="fa fa-graduation-cap"></i>'.html_safe if service.servtitle.parameterize == "golf-lessons" %>
                              <%= '<i class="fa fa-car"></i>'.html_safe if service.servtitle.parameterize == "buggy-cart-hire" %>
                              <%= '<i class="fa fa-hand-paper-o"></i>'.html_safe if service.servtitle.parameterize == "custom-fitting" %>
                              <%= '<i class="fa fa-area-chart"></i>'.html_safe if service.servtitle.parameterize == "trackman-flightscope" %>
                              <%= '<i class="fa fa-wrench"></i>'.html_safe if service.servtitle.parameterize == "club-repair" %>
                              <%= '<i class="fa fa-comment"></i>'.html_safe if service.servtitle.parameterize == "after-dinner-speaking" %>
                              <%= '<i class="fa fa-flag"></i>'.html_safe if service.servtitle.parameterize == "pratice-facilities" %>
                              <%= service.servtitle %>
                            </li>
                          <% end %>
                        </ul>
                    </div>
                <hr/>
                <%= @profile.bio.html_safe %>
             </div>
          </div>  

          <div class="ibox float-e-margins">
              <div class="ibox-title">
                  <h5>Addidtional Information <span class="showtooltip" data-toggle="tooltip" data-placement="top" title="Information your provide that is stored in our system"><i class="fa fa-question-circle"></i></span></h5>
                  <p class="note"><small><strong>Note:</strong> This information is not displayed on your public profile.</small></p>
              </div>
              <div class="ibox-content">

                  <div>
                      <div class="feed-activity-list">
                            <dl class="dl-horizontal m-t-md small">
                                <dt>Phone Number</dt>
                                <dd><%= @profiles.phone %></dd>
                                <dt>Position at Club</dt>
                                <dd><%= (@profiles.position == 1? 'Club Pro': 'Pro Assistant') %></dd>
                                <dt>Club Postcode</dt>
                                <dd><%= @profiles.postcode %></dd>
                            </dl>
                      </div>

                  </div>

              </div>
          </div>

      </div>
  </div>
</div>

<div class="modal inmodal fade" id="statusUpdate" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <form id="feedback_form" novalidate="novalidate" accept-charset="UTF-8">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">New Status Post</h4>
                </div>
                <div class="modal-body">
                    <div id="loadingImg" class="loading hide">
                       <div class="progress">
                          <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                          </div>
                        </div>
                    </div>
                    <div class="row center-block text-center">
                        <textarea class="message col-xs-12" rows="2" cols="30" placeholder="What's Happening?"></textarea>
                        <span class="countdown"></span>
                    </div>
                </div>  

                <div class="modal-footer">
                    <button type="cancel" class="btn btn-white" data-dismiss="modal">Close</button>
                    <button type="submit" data-id="<%= @profile.id %>" id="postStatus" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
      var proLat = <%= @profile.latitude %>;
      var proLon = <%= @profile.longitude %>;
</script>

<% content_for :javascript do %>

  <script type="text/javascript">

      $(document).ready(function(){

        <% if !params[:tour].blank? %>
            theTour()
        <% end %>

      });

  </script>

<% end %>