config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :classifieds
  devise_for :users, controllers: { registrations: "registrations", :omniauth_callbacks => "omniauth_callbacks"  }, path_names: { sign_up: ''}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#home'
  
   %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'my-profile', to: 'profiles#profileoverview'

  get 'dashboard', to: 'dashboard#index'

  get 'signup', to: 'pages#signup'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
    get 'logout', to: 'devise/sessions#destroy'
  end

  get 'search', to: 'search#search'
  get 'search/autocomplete', to: 'search#autocomplete'

  post 'classifieds/product/confirm', to: 'classifieds#confirmPurchase'

  get 'users/upgrade', to: 'subscription#upgrade'
  get 'users/subscribe/confirm', to: 'subscription#confirm'
  get 'users/subscribe/success', to: 'subscription#success'
  get 'users/subscribe/error', to: 'subscription#error'
  post 'users/subscribe/', to: 'subscription#subscribe'
  post 'classifieds/payment/confirmation/:id', to: 'classifieds#stripeProcess'
  get 'classifieds/addons/confirm', to: 'classifieds#addonConfirm'
  get 'profile/gallery', to: 'profiles#galleryOverview'
  get 'invoices', to: 'classifieds#soldInvoices'
  get 'invoices/view/:id', to: 'classifieds#viewInvoice'
  put 'invoices/refund/:id', to: 'classifieds#processRefund'
  get 'purchase/:id/thankyou', to: 'classifieds#thankyou'

  post 'classifieds/:id/addons', to: 'classifieds#processAddon'
  get 'update_cats', to: 'classifieds#update_cats',  :defaults => { :format => 'json' }
  get 'ebaygetitem', to: 'classifieds#getebayitem',  :defaults => { :format => 'json' }
  get 'gbgetitem', to: 'classifieds#getgbitem',  :defaults => { :format => 'json' }
  get 'changeArchive', to: 'classifieds#changeArchive', :defaults => { :format => 'json' }
  get 'smartSearch', to: 'search#ajaxSearch', :defaults => { :format => 'json' }
  post 'submithelp', to: 'application#create_groove_ticket', :defaults => { :format => 'json' }
  post 'addonCreditsProcess', to: 'classifieds#processAddonCredits'
  post 'getBlogPosts', to: 'pages#getBlogPost',  :defaults => { :format => 'json' }
  get 'profile/:userid/gallery/:imgid/delete', to: 'profiles#galleryImageDelete', :defaults => {:format => 'json'}
  post 'profile/:id/gallery/new', to: 'profiles#galleryImageUpload', :defaults => {:format => 'json'}
  delete 'classifieds/:id/images/:imgid', to: 'classifieds#extraImageDelete', :defaults => {:format => 'json'}
  post 'profile/:id/status', to: 'profiles#createNewStatus', :defaults => {:format => 'json'}
  delete 'profile/status/:statusid', to: 'profiles#deleteStatus', :defaults => {:format => 'json'}
  post 'users/:userid/subscribe/cardchange',  to: 'subscription#cardChange', :defaults => {:format => 'json'}
  post 'profiles/:id/contact', to: 'profiles#emailContact', :defaults => {:format => 'json'}

end

app/views/transactionals/addon_purchase.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
<head>
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><%= @company %> - Your Addon Purchase Reciept</title>


<style type="text/css">
img {
max-width: 100%;
}
body {
-webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6em;
}
body {
background-color: #f6f6f6;
}
@media only screen and (max-width: 640px) {
  body {
    padding: 0 !important;
  }
  h1 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h2 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h3 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h4 {
    font-weight: 800 !important; margin: 20px 0 5px !important;
  }
  h1 {
    font-size: 22px !important;
  }
  h2 {
    font-size: 18px !important;
  }
  h3 {
    font-size: 16px !important;
  }
  .container {
    padding: 0 !important; width: 100% !important;
  }
  .content {
    padding: 0 !important;
  }
  .content-wrap {
    padding: 10px !important;
  }
  .invoice {
    width: 100% !important;
  }
}
</style>
</head>

<body itemscope itemtype="http://schema.org/EmailMessage" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; line-height: 1.6em; background-color: #f6f6f6; margin: 0;" bgcolor="#f6f6f6">

<table class="body-wrap" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; background-color: #f6f6f6; margin: 0;" bgcolor="#f6f6f6"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>
    <td class="container" width="600" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto;" valign="top">
      <div class="content" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; max-width: 600px; display: block; margin: 0 auto; padding: 20px;">
        <table class="main" width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; border-radius: 3px; background-color: #fff; margin: 0; border: 1px solid #e9e9e9;" bgcolor="#fff"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-wrap aligncenter" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; text-align: center; margin: 0; padding: 20px;" align="center" valign="top">
              <table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px; text-align:center;" valign="top">
                    <img src="https://s3-eu-west-1.amazonaws.com/pro-finder-golf/email/logo.png" width="50%" style="margin: 0 auto;" />
                  </td>
                </tr>
                <tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
                    <h2>Thanks for your addon purchase!</h2>
                  </td>
                </tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
                    Hi <%= @profile.name %>, thanks for buying addons for your advert. You have helped ensure you advert gets maximum coverage on <%= @company_domain %>. A receipt of your purchase can be found below:
                  </td>
                </tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block aligncenter" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; text-align: center; margin: 0; padding: 0 0 20px;" align="center" valign="top">
                    <table class="invoice" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; text-align: left; width: 80%; margin: 0px auto 0px;"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 5px 0;" valign="top"><%= @profile.name %><br style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" /><%= @profile.golfclub %><br style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" /><%= @address.first.city %><br style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" /><%= @address.first.sub_state %><br style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" /><%= Time.now.strftime('%d/%m/%Y') %></td>
                      </tr><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 5px 0;" valign="top">
                          <table class="invoice-items" cellpadding="0" cellspacing="0" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; margin: 0;">
                            <% price = 0 %>
                            <% @addons.each do |addon| %>
                                <% price += addon.price %>
                                <tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; border-top-width: 1px; border-top-color: #eee; border-top-style: solid; margin: 0; padding: 5px 0;" valign="top"><%= addon.name %></td>
                                  <td class="alignright" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; text-align: right; border-top-width: 1px; border-top-color: #eee; border-top-style: solid; margin: 0; padding: 5px 0;" align="right" valign="top"><%= number_to_currency(addon.price*@days, unit: "£", locale: :uk) %>(<%= number_to_currency(addon.price, unit: "£", locale: :uk) %> pr/day)</td>
                                </tr>
                            <% end %>
                            <tr class="total" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td  width="30%" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; text-align: left; border-top-width: 2px; border-top-color: #333; border-top-style: solid; border-bottom-color: #333; border-bottom-width: 2px; border-bottom-style: solid; font-weight: 700; margin: 0; padding: 5px 0;" align="left" valign="top">Total</td><td class="alignright" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; text-align: right; border-top-width: 2px; border-top-color: #333; border-top-style: solid; border-bottom-color: #333; border-bottom-width: 2px; border-bottom-style: solid; font-weight: 700; margin: 0; padding: 5px 0;" align="right" valign="top"><%= number_to_currency(price*@dayDist, unit: "£", locale: :uk) %></td>
                            </tr></table></td>
                      </tr></table></td>
                </tr>
                <tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="content-block aligncenter" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; text-align: left; margin: 0; padding: 0 0 20px;" align="center" valign="top">
                    We are always here to help. So if you have any queries about your purchase, feel free to drop us an email through our help desk. From the <%= @company %> website, head to <strong>Help</strong> / <strong>Submit Help Ticket</strong> and let us know what's on your mind.
                  </td>
                </tr></table></td>
          </tr></table><div class="footer" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; width: 100%; clear: both; color: #999; margin: 0; padding: 20px;">
          <table width="100%" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><tr style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;"><td class="aligncenter content-block" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 12px; vertical-align: top; color: #999; text-align: center; margin: 0; padding: 0 0 20px;" align="center" valign="top"><a style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 12px; color: #999; text-decoration: underline; margin: 0;" href="https://www.facebook.com/profindergolf" target="_blank">Facebook</a>, <a href="https://www.twitter.com/profindergolf" target="_blank" style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 12px; color: #999; text-decoration: underline; margin: 0;">Twitter</a>, <a style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 12px; color: #999; text-decoration: underline; margin: 0;" href="https://www.instagram.com/profindergolf" target="_blank">Instagram</a> and <a style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 12px; color: #999; text-decoration: underline; margin: 0;" href="https://www.youtube.com/c/profindergolf" target="_blank">Youtube</a><br/><br/>© <%= Time.now.year %> <%= @company %></td>
            </tr></table></div></div>
    </td>
    <td style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0;" valign="top"></td>
  </tr></table></body>
</html>

app/views/transactionals/addon_purchase.text.erb
** Thanks for your addon purchase!
------------------------------------------------------------
Hi <%= @profile.name %>, thanks for buying addons for your advert. You have helped ensure you advert gets maximum coverage on <%= @company_domain %>. A receipt of your purchase can be found below:
<%= @profile.name %>
<%= @profile.golfclub %>
<%= @address.first.city %>
<%= @address.first.sub_state %>
<%= Time.now.strftime('%d/%m/%Y') %>

---
<% price = 0 %>
<% @addons.each do |addon| %>
<% price += addon.price %>
  <%= addon.name %> | <%= number_to_currency(addon.price*@days, unit: "£", locale: :uk) %> (<%= number_to_currency(addon.price, unit: "£", locale: :uk) %> pr/day)
<% end %>
Total: <%= number_to_currency(price*@dayDist, unit: "£", locale: :uk) %>
---

We are always here to help. So if you have any queries about your purchase, feel free to drop us an email through our help desk. From the <%= @company %> website, head to Help / Submit Help Ticket and let us know what's on your mind.
Facebook (https://www.facebook.com/profindergolf) , Twitter (https://www.twitter.com/profindergolf) , Instagram (https://www.instagram.com/profindergolf) and Youtube (https://www.youtube.com/c/profindergolf)

© <%= Time.now.year %> <%= @company %>

app/views/transactionals/confirmation_instructions.html.erb
<p>Welcome <%= @email %>!</p>

<p>You can confirm your account email through the link below:</p>

<p><%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>

app/views/transactionals/customer_item_purchase.text.erb
** Thanks for your purchase!
------------------------------------------------------------
Hi <%= @params['source']['name'] %>, thanks so much for your purchase on <%= @company_domain %>. By buying an item from <%= @company %> you are ensuring that you receive the best items at a fair price. Please find a copy of your order below:
---
<%= @params['source']['name'] %>
<%= @params['source']['address_line1'] %><% if !@params['source']['address_line2'].blank? %>
<%= @params['source']['address_line2'] %><% end %>
<%= @params['source']['address_city'] %>
<%= Time.now.strftime('%d/%m/%Y') %>
---
<%= @product.adtitle %> Total <%= number_to_currency(@product.price, unit: "£", locale: :uk) %>

Your item is for collection only. This means you will need to collect your item from its seller's location. You can collect your item at the following address:

<%= @seller.name %>
<%= @seller.golfclub %>
<%= @address.html_safe %>
<%= @sellerEmail %>

--
Hey thanks for placing your order with me. My aim is to provide products that will help improve your game. If you have any questions about your item, please feel free to contact myself at: mailto:<%= @sellerEmail %>. If you'd like a refund on your purchase, please contact myself on the same email address. Thanks again and enjoy your purchase!
<%= @seller.name %>
--

We are always here to help. So if you have any queries about your purchase, feel free to drop us an email through our help desk. From the <%= @company %> website, head to Help / Submit Help Ticket and let us know what's on your mind.
Facebook (https://www.facebook.com/profindergolf) , Twitter (https://www.twitter.com/profindergolf) , Instagram (https://www.instagram.com/profindergolf) and Youtube (https://www.youtube.com/c/profindergolf)

To help us improve our systems, we would love it if you could complete a quick survey about your experience on Pro Finder Golf. You can view the survey here: 

https://insights.hotjar.com/s?siteId=174359&surveyId=9220 

We would really be grateful if you can take some time out to let us know your thoughts.

© <%= Time.now.year %> <%= @company %>

app/views/transactionals/new_pro_email.text.erb
** Welcome to <%= @company %> - Your Account Information
------------------------------------------------------------

We are pleased to confirm that your FREE account on <%= @company %> has been successfully created. Now you are ready to log in and start customising your profile. So what are you waiting for? Click the button below to get started!

<%= @login %>

Your login details are:

Username: <%= @email %>

Password: <%= @password %>

You can change your password at any time by heading to "My Account / Edit Account". You can also change your contact and login email there. NOTE: to help protect your profile we suggest reading over the Google Guide "Creating a strong password" [https://support.google.com/accounts/answer/32040?hl=en] if you wish to change your password. The advice given in this guide will help protect your account from intruders.

We have attached a few guides to help get you started with promoting your services and selling your adverts. We are always here to help, so if you have any questions feel free to get in touch through our help desk. You create a ticket by going to "Help / Submit Help Ticket". We also have a list of Frequently Asked Questions (FAQs) that may have answers you are looking for. You can find these under "Help / FAQ" from our website.

Be sure to follow us on our social media channels to stay up to date and to get access to the latest and exclusive content: Facebook [https://www.facebook.com/profindergolf], Twitter [https://www.twitter.com/profindergolf], Instagram [https://www.instagram.com/profindergolf] and Youtube [https://www.youtube.com/c/profindergolf]. 

Thanks for choosing Pro Finder Golf.

- The Profinder.golf Team

© <%= Time.now.year %> <%= @company %>

app/views/transactionals/password_change.html.erb
<p>Hello <%= @resource.email %>!</p>

<p>We're contacting you to notify you that your password has been changed.</p>

app/views/transactionals/pro_account_change.text.erb
** Account Plan Changed
------------------------------------------------------------

** We can confirm your account subscription plan has changed to <%= @planTitle %>.

Information about your new charges can be found below.

New Account Plan
<%= Time.now.strftime('%d%m%Y') %>
----
<%= @planTitle %> <%= number_to_currency(@price, unit: "£", locale: :uk) %>/mo
Total <%= number_to_currency(@price, unit: "£", locale: :uk) %>/mo
----

We are always here to help. So if you have any queries about your monthly subscription, feel free to drop us an email through our help desk. From the <%= @company %> website, head to "Help" / "Submit Help Ticket" and let us know what's on your mind.

Follow us on:
Facebook (https://www.facebook.com/profindergolf) 
Twitter (https://www.twitter.com/profindergolf)
Instagram (https://www.instagram.com/profindergolf) 
Youtube (https://www.youtube.com/c/profindergolf)

© <%= Time.now.year %> <%= @company %>

app/views/transactionals/pro_contact.text.erb
** Pro Finder Golf - Vistor Contact Message
------------------------------------------------------------
Hi, <%= @proname %>, someone has sent a contact message to you. See below for all the details of this contact:
------------------------------------------------------------
Email: <%= @user %> 
Subject: <%= @subject %> 

Message:
<%= @themessage %>

---

You can reply to this enquirer by simply replying to this email or create a new email and send it to the email outlined above, whatever suits you.
We ask if you can be courteous and helpful at all times when interacting with the customer. Many <%= @company %> customers are new to golf so please bare this in mind when in conversation with the customer.

We are always here to help. So if you have any problems with the transaction or with the customer, feel free to drop us an email through our help desk. From the <%= @company %> website, head to Help / Submit Help Ticket and let us know how we can help you out.

Be sure to follow us on our social media channels to stay up to date and to get access to the latest and exclusive content: Facebook (https://www.facebook.com/profindergolf) , Twitter (https://www.twitter.com/profindergolf) , Instagram (https://www.instagram.com/profindergolf) and Youtube (https://www.youtube.com/c/profindergolf) .
Thanks for choosing Pro Finder Golf.
- The Profinder.golf Team

Facebook (https://www.facebook.com/profindergolf) , Twitter (https://www.twitter.com/profindergolf) , Instagram (https://www.instagram.com/profindergolf) and Youtube (https://www.youtube.com/c/profindergolf)

<%= Time.now.year %> <%= @company %>

app/views/transactionals/reset_password_instructions.text.erb
** Password Reset
------------------------------------------------------------
Hey <%= @email %>,

We received a password request for your account. If you are expecting an email about resetting your password, good news! You can click on the button below to change your password to a more memorable one right now:

Change My Password (<%= edit_password_url(@resource, reset_password_token: @token) %>)

Don't panic if you weren't expecting this email! Nothing has changed yet, so if someone is being naughty and trying to reset your password without your permission, just delete this email and carry on with your day as normal. No sweat.

Account security is very important to us here at <%= @company %> so if you have any worries about your account security or think something fishy is going on, feel free to drop us an email through our help desk. From the <%= @company %> website, head to "Help" / "Submit Help Ticket" and let us know what's making your feel uneasy.

Thanks again for choosing to work with Pro Finder Golf.
— The Profinder.golf Team

PSST! Are you following us on our social media channels? If you're not, you're missing out on some exclusive content! Check us out at: Facebook (https://www.facebook.com/profindergolf), Twitter (https://www.twitter.com/profindergolf) , Instagram (https://www.instagram.com/profindergolf) and Youtube (https://www.youtube.com/c/profindergolf) .

© <%= Time.now.year %> <%= @company %>

app/views/transactionals/seller_item_purchase.text.erb
** Your Item Has Sold!
------------------------------------------------------------
Hi <%= @seller.name %>, your item "<%= @product.adtitle %>" has been sold, congratulations! Please find a copy of the order information below. Note: you can find a copy of this invoice from your <%= @company %> account under the "Sold Invoices" section.

---
<%= @params['source']['name'] %>
<%= @params['source']['address_line1'] %><% if !@params['source']['address_line2'].blank? %>
<%= @params['source']['address_line2'] %><% end %>
<%= @params['source']['address_city'] %>
<%= Time.now.strftime('%d/%m/%Y') %>
---

<%= @product.adtitle %> Total <%= number_to_currency(@product.price, unit: "£", locale: :uk) %>
This item is for collection only. This means the buyer need to collect your item from the location we have on our systems for you:

--
<%= @seller.name %>
<%= @seller.golfclub %>
<%= @address.html_safe %>
<%= @sellerEmail %>
--

We ask if you can be courteous and helpful at all times when interacting with the customer. Many <%= @company %> customers are new to golf so please bare this in mind when in conversation with the customer.
We are always here to help. So if you have any problems with the transaction or with the customer, feel free to drop us an email through our help desk. From the <%= @company %> website, head to Help / Submit Help Ticket and let us know how we can help you out.
Facebook (https://www.facebook.com/profindergolf) , Twitter (https://www.twitter.com/profindergolf) , Instagram (https://www.instagram.com/profindergolf) and Youtube (https://www.youtube.com/c/profindergolf)

© <%= Time.now.year %> <%= @company %>

app/views/transactionals/unlock_instructions.html.erb
<p>Hello <%= @resource.email %>!</p>

<p>Your account has been locked due to an excessive number of unsuccessful sign in attempts.</p>

<p>Click the link below to unlock your account:</p>

<p><%= link_to 'Unlock my account', unlock_url(@resource, unlock_token: @token) %></p>