config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :classifieds
  devise_for :users, controllers: { registrations: "registrations", :omniauth_callbacks => "omniauth_callbacks"  }, path_names: { sign_up: ''}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#home'
  
   %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'my-profile', to: 'profiles#profileoverview'

  get 'dashboard', to: 'dashboard#index'

  get 'signup', to: 'pages#signup'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
    get 'logout', to: 'devise/sessions#destroy'
  end

  get 'search', to: 'search#search'
  get 'search/autocomplete', to: 'search#autocomplete'

  post 'classifieds/product/confirm', to: 'classifieds#confirmPurchase'

  get 'users/upgrade', to: 'subscription#upgrade'
  get 'users/subscribe/confirm', to: 'subscription#confirm'
  get 'users/subscribe/success', to: 'subscription#success'
  get 'users/subscribe/error', to: 'subscription#error'
  post 'users/subscribe/', to: 'subscription#subscribe'
  post 'classifieds/payment/confirmation/:id', to: 'classifieds#stripeProcess'
  get 'classifieds/addons/confirm', to: 'classifieds#addonConfirm'
  get 'profile/gallery', to: 'profiles#galleryOverview'
  get 'invoices', to: 'classifieds#soldInvoices'
  get 'invoices/view/:id', to: 'classifieds#viewInvoice'
  put 'invoices/refund/:id', to: 'classifieds#processRefund'
  get 'purchase/:id/thankyou', to: 'classifieds#thankyou'

  post 'classifieds/:id/addons', to: 'classifieds#processAddon'
  get 'update_cats', to: 'classifieds#update_cats',  :defaults => { :format => 'json' }
  get 'ebaygetitem', to: 'classifieds#getebayitem',  :defaults => { :format => 'json' }
  get 'gbgetitem', to: 'classifieds#getgbitem',  :defaults => { :format => 'json' }
  get 'changeArchive', to: 'classifieds#changeArchive', :defaults => { :format => 'json' }
  get 'smartSearch', to: 'search#ajaxSearch', :defaults => { :format => 'json' }
  post 'submithelp', to: 'application#create_groove_ticket', :defaults => { :format => 'json' }
  post 'addonCreditsProcess', to: 'classifieds#processAddonCredits'
  post 'getBlogPosts', to: 'pages#getBlogPost',  :defaults => { :format => 'json' }
  get 'profile/:userid/gallery/:imgid/delete', to: 'profiles#galleryImageDelete', :defaults => {:format => 'json'}
  post 'profile/:id/gallery/new', to: 'profiles#galleryImageUpload', :defaults => {:format => 'json'}
  delete 'classifieds/:id/images/:imgid', to: 'classifieds#extraImageDelete', :defaults => {:format => 'json'}
  post 'profile/:id/status', to: 'profiles#createNewStatus', :defaults => {:format => 'json'}
  delete 'profile/status/:statusid', to: 'profiles#deleteStatus', :defaults => {:format => 'json'}
  post 'users/:userid/subscribe/cardchange',  to: 'subscription#cardChange', :defaults => {:format => 'json'}
  post 'profiles/:id/contact', to: 'profiles#emailContact', :defaults => {:format => 'json'}

end

app/models/classifieds.rb
class Classifieds < ActiveRecord::Base

	before_create :randomize_id

	paginates_per 20

	max_paginates_per 20
	
	belongs_to :user

	has_many :classadtag, :dependent => :destroy
	has_many :tag, through: :classadtag

	has_many :brandrel, :dependent => :destroy
	has_many :brand, through: :brandrel

	has_many :advertaddon, :dependent => :destroy
	has_many :addons, through: :advertaddon

	belongs_to :images, :foreign_key => :image, :dependent => :destroy

	belongs_to :classtypes, :foreign_key => :adtype
	belongs_to :classcat, :foreign_key => :cat

	has_many :analytic

	before_destroy :destroy_assocs
	before_create :set_default_enddate

	searchkick  callbacks: false, suggest: [:adtitle, :brandname], highlight: [:adtitle, :brandname, :description], word_start: [:adtitle, :tags, :description, :brandname], locations: ["location"], boost_where: {featured: {value: 1, factor: 100}}, match: :word_start, searchable: [:adtitle, :description, :tag, :classcats, :brandname]

	after_save :reindex, if: proc{|model| model.status == 1 }
	after_destroy :reindex

	def search_data
		featured = 0
		self.addons.each do |addon|
			if addon.name.downcase == 'featured'
				featured = 1
			end
		end
		attributes.merge(tags: tag.map(&:tagname), brandname: brand.map(&:brandname), category: classcat.classname, category_parent: classtypes.typename, location: {lat: user.profile.latitude, lon: user.profile.longitude}, featured: featured, profeatured: self.user.profile.featured)

	end

	def should_index?
    	status == 1
  	end

	def destroy_assocs
		self.images.destroy if self.images != nil 
		self.images.delete if self.images != nil 
		self.classadtag.delete_all  if self.classadtag != nil 
	end

	def set_default_enddate
		self.enddate = Time.now
	end

	def self.ad_date_check
		ads = self.where(["enddate < ?", 2.days.ago])
		for ad in ads
			ad.status = 0
			ad.save
			Classifieds.searchkick_index.remove(ad)
		end
		Classifieds.reindex
	end

	private
		def randomize_id
		  begin
		    self.id = SecureRandom.random_number(1_000_000)
		  end while Classifieds.where(id: self.id).exists?
		end

end

	#Classifieds.reindex

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
	require 'sanitize'
	require 'json'

	before_action :authenticate_user!, except: [:show, :update_cats, :confirmPurchase, :stripeProcess, :thankyou]
	before_action :check_account_level, only: [:new, :create]

	respond_to :html, :json

	def index
		@classAds = Classifieds.where(user_id: current_user.id)
		@limit = @profile.plans.ads <= @classAds.size ? true : false
		if !@classAds.nil?
			@classAds = @classAds.order('created_at').page(params[:page]).per(10)
		end
	end

	def show
		@classAd = Classifieds.find_by_id_and_status(params[:id], 1) or not_found
		@images = Images.where(id: @classAd.image).take
		@extraImgs = Adextraimgs.where(classifieds_id: @classAd.id).order("created_at ASC")

		@classTypes = Classtypes.all
		@tags = Tag.all
		if !@classAd.nil? and !@classAd.adtype.nil?
			@classCats = Classcat.where("parenttype= ?", @classAd.adtype)
		end
		@brands = Brand.all
		if @images.nil? 
			@image = Images.new
		end

		event = Analytic.new
		event.analytic_type = 2
		if !cookies[:classAnalytics]
			event.identifier = SecureRandom.hex
			cookies[:classAnalytics] = event.identifier
		else
			event.identifier = cookies[:classAnalytics]
		end
		event.profiles_id = @classAd.user.profile.id
		event.classifieds_id = @classAd.id
		event.properties = {test: '123'}
		event.save

	end

	def new
		@classformpath = classifieds_path
		@classAd = Classifieds.new
		@classTypes = Classtypes.all
		@tags = Tag.all
		@addons = Addons.all
		@brands = Brand.all
		@image = Images.new
		@limitNum = @profile.plans.photos
		@limit = false
		@classAd.adtype = 0
	end

	def edit
		@classformpath = classified_path
		@classAd = Classifieds.find_by_id_and_user_id(params[:id], current_user.id)
		@images = Images.find_by_id(@classAd.image)
		@extraImgs = Adextraimgs.where(classifieds_id: @classAd.id).order("created_at DESC")
		@limit = @profile.plans.photos <= @extraImgs.size ? true : false
		@limitNum = @profile.plans.photos
		@classTypes = Classtypes.all
		@addons = Addons.all
		@tags = Tag.all
		if !@classAd.adtype.blank?
			@classCats = Classcat.where("parenttype= ?", @classAd.adtype)
		end
		@brands = Brand.all
		if @image.nil?
			@image = Images.new
		end
	end

	def create

		@imageDetails = ''

		if !params[:classifieds][:theimage].blank?
			image = Images.new()
			image.user_id = current_user.id
			image.theimage = params[:classifieds][:theimage]
			image.protype = 'classimg'
			if image.save
			   	checking = true
			else
			    checking = false
			end
		end

		if !params[:classifieds][:remote_url].blank?
			image = Images.new()
			image.user_id = current_user.id
			image.protype = 'classimg'
			image.remote_theimage_url = params[:classifieds][:remote_url]
			image.save
		end	

		classAd = Classifieds.new(classad_params)
		classAd.user_id = current_user.id
		classAd.status = 1
		if !image.blank?
			classAd.image = image.id
		end

		classAd.url = classAd.url.gsub(/\?.*/, '')
		if classAd.save

			if !params[:classifieds][:extraImage].blank?
				params[:classifieds][:extraImage].each do |exImg|
					images = Adextraimgs.where(classifieds_id: classAd.id)
					limit = @profile.plans.photos <= images.size ? true : false

					if !limit
						image = Images.new(theimage: exImg[:data])
						image.user_id = current_user.id
						image.protype = 'adextraimg'
						if image.save
							adextraimg = Adextraimgs.new()
							adextraimg.classifieds_id = classAd.id
							adextraimg.images_id = image.id
							adextraimg.save
							checking = true
						else
							checking = false
						end 
					end
				end
			end
			
			if !params[:classifieds][:brand].blank?
				brandrel = Brandrel.new()
				brandrel.classifieds_id = classAd.id
				brandrel.brand_id = params[:classifieds][:brand]
				if brandrel.save
					checking = true
				else
					checking = false
				end
			end

			if !params[:classifieds][:tags].blank?
				params[:classifieds][:tags].each do |tag|
					classtags = Classadtag.new()
					classtags.classifieds_id = classAd.id
					classtags.tag_id = tag
					if classtags.save
						checking = true
					else
						checking = false
					end
				end
			end

			if !params[:addon].blank?
				ads = []
				params[:addon].each do |key, value|
					ads.push((value.to_f)/100)
				end
				params[:id] = classAd.id
				@addons = Addons.where(price: ads)

				date1 = (params[:classifieds][:enddate].to_datetime.strftime('%Q').to_f)/1000
				date2 = (Time.now.utc.to_s(:db).to_datetime.strftime('%Q').to_f)/1000

				@dayDist = ((((date1 - date2)/60)/60)/24).ceil
				params[:credits] = @dayDist*params[:addon].count
				#redirect_to "/classifieds/#{@classAd.id}/addons", addon: params[:addon], notice: 'Your Advert has been saved'
				render 'classifieds/addonProcess',  notice: 'Your Advert has been saved. Please confirm your addon purchases'
			else
				redirect_to classifieds_path, notice: 'Your Advert was updated successfully.'
			end
		else
			render :action => 'new', :notice => 'there was a problem'
		end
	end

	def update
		checking = true

		@classAd = Classifieds.find_by_id_and_user_id(params[:id], current_user.id)

		if !params[:classifieds][:theimage].blank?

			theimage = Images.exists?( :id => @classAd.image )
			if theimage
				destroyImg = Images.find(@classAd.image).destroy
			end
			image = Images.new()
			image.user_id = current_user.id
			image.theimage = params[:classifieds][:theimage]
			image.protype = 'classimg'
			if image.save
			   	checking = true
				@classAd.image = image.id
			else
			    checking = false
			end
		end

		if !params[:classifieds][:remote_url].blank?
			images = Images.find_by_id(@classAd.image)
			if !images.blank?
				images.remove_theimage!
				images.destroy
			end
			image = Images.new()
			image.user_id = current_user.id
			image.protype = 'classimg'
			image.remote_theimage_url = params[:classifieds][:remote_url]
			image.save
			@classAd.image = image.id
		end

		if !params[:classifieds][:extraImage].blank?
			params[:classifieds][:extraImage].each do |img|
				images = Adextraimgs.where(classifieds_id: @classAd.id)
				@limit = @profile.plans.photos <= images.size ? true : false

				if !@limit
					image = Images.new(theimage: img[:data])
					image.user_id = current_user.id
					image.protype = 'adextraimg'
					if image.save
						adextraimg = Adextraimgs.new()
						adextraimg.classifieds_id = @classAd.id
						adextraimg.images_id = image.id
						adextraimg.save
						checking = true
					else
						checking = false
					end 
				end
			end
		end

		if !@classAd.tag.blank?
			@classAd.tag.clear
		end

		if !params[:classifieds][:tags].blank?
			params[:classifieds][:tags].each do |tag|
				classtags = Classadtag.new()
				classtags.classifieds_id = params[:id]
				classtags.tag_id = tag
				if classtags.save
					checking = true
				else
					checking = false
				end
			end
		end

		if !@classAd.brand.blank?
			@classAd.brand.clear
		end

		if !params[:classifieds][:brand].blank?
			brandrel = Brandrel.new()
			brandrel.classifieds_id = params[:id]
			brandrel.brand_id = params[:classifieds][:brand]
			if brandrel.save
				checking = true
			else
				checking = false
			end
		end

		params[:classifieds][:description] = Sanitize.fragment(params[:classifieds][:description], Sanitize::Config::RESTRICTED)

		if @classAd.enddate.to_date.future?
			@classAd.status = 1
		else
			Classifieds.searchkick_index.remove(@classAd)
		end

		if @classAd.update(classad_params)
			checking = true
		else
			checking = false
		end

		redirect_to classifieds_path, notice: 'Your Advert was updated successfully.'
		return false
	end

	def confirmPurchase
		@product = Classifieds.find_by_id_and_status(params[:prod][:id], 1) or not_found
		@images = Images.where(id: @product.image).take
	end

	def processAddon
		if params[:id].kind_of?(Array) 
			ids = eval(params[:aid])
		else
			ids = params[:aid] 
		end
		
		addons = Addons.where(id: ids)

		if !addons.nil?

			price = addons.sum(:price)

			date1 = (params[:enddate].to_datetime.strftime('%Q').to_f)/1000
			date2 = (Time.now.utc.to_s(:db).to_datetime.strftime('%Q').to_f)/1000

			@dayDist = ((((date1 - date2)/60)/60)/24).ceil

			begin

				Stripe.api_key = Rails.configuration.stripe[:secret_key]
				Stripe::Charge.create({
				  :amount => (price*100).to_i,
				  :currency => "gbp",
				  :source => params[:stripeToken]
				})

	        rescue Stripe::CardError => e
				flash[:error] = e.message
				render js: "window.location = '#{classifieds_path}'"
				#redirect_to classifieds_path, notice: 'There was an error in completing the addon purchase'
				return
			else

				Transactionals.addon_purchase(addons,params,@profile,price,@dayDist,false).deliver_now

				addons.each do |addon|
					adAddons = Advertaddon.new()
					adAddons.classifieds_id = params[:id]
					adAddons.addons_id = addon.id
					adAddons.save
				end
				flash[:success] = "Thank You, you addons have now been activated on your advert."
				render js: "window.location = '#{classifieds_path}'"
				#redirect_to classifieds_path, :notice => 'Thank You, you addons have now been activated on your advert.'
			end
		else
			flash[:error] = 'There was an error in completing the addon purchase'
			render js: "window.location = '#{classifieds_path}'"
			#redirect_to classifieds_path, notice: 'There was an error in completing the addon purchase'
		end
	end

	def processAddonCredits
		ids = eval(params[:aid])

		addons = Addons.where(id: ids)


		date1 = (params[:enddate].to_datetime.strftime('%Q').to_f)/1000
		date2 = (Time.now.utc.to_s(:db).to_datetime.strftime('%Q').to_f)/1000

		@dayDist = ((((date1 - date2)/60)/60)/24).ceil
		credits =  @dayDist*addons.count

		if !addons.nil?

			if @profile.adcredits - credits > 0 
				
				@profile.adcredits = @profile.adcredits - credits
				@profile.save

				addons.each do |addon|
					adAddons = Advertaddon.new()
					adAddons.classifieds_id = params[:adid]
					adAddons.addons_id = addon.id
					adAddons.save
				end	

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/views/classifieds/edit.html.erb
<div id="alert-append" class="wrapper wrapper-content container animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    <h2>
                        Edit Product Advert
                    </h2>
                    <p>
                        Use the fields below to edit your advert. <strong>NOTE:</strong> if you make any changes and save the advert's changes, they will be made live immediately.
                    </p>
					<%= render 'form' %>
				</div>
            </div>
        </div>

    </div>
</div>

app/views/classifieds/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="container">
        <h2>My Product Adverts</h2>
        <ol class="breadcrumb">
            <li>
                <% if user_signed_in? %><li><%= link_to "Dashboard", dashboard_path %></li><% end %> 
            </li>
            <li class="active">
                <strong>My Product Adverts</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content container animated fadeInRight">
    
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox" ID="tour-class">
                <div class="ibox-title">
                    <h5>My Pro Adverts</h5>
                    <div class="ibox-tools">
                        <% if !@limit %>
                          <a href="<%= new_classified_path %>" class="btn btn-primary btn-md ladda-button" data-style="expand-right"><span class="ladda-label">Create New Advert</span></a>
                        <% else %>
                          <span class="showtooltip" data-toggle="tooltip" data-placement="top" title="You have reached your advert limit. Please upgrade your account to make more.">
                            <%= link_to "Create new Advert", new_classified_path, class: "btn btn-primary btn-md disabled" %>
                          </span>
                        <% end %>
                    </div>
                </div>
                <div class="ibox-content">

                    <div class="m-b-lg">

                        <!-- this may get added in future updates <div class="input-group">
                            <input type="text" placeholder="Search advert by name..." class=" form-control">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-white"> Search</button>
                            </span>
                        </div>-->
                        <div class="m-t-md">

                            <div class="pull-right" id="the-actions">
                                <%= link_to edit_classified_path(0), class: "btn btn-white change-id" do %>
                                  <i class="fa fa-pencil-square-o"></i> Edit
                                <% end %>
                                <%= link_to classified_path(0), method: :delete, class: "btn btn-white change-id delete-url", id: 'addelete', :onclick => 'return false;'  do %>
                                  <i class="fa fa-trash-o"></i> Delete
                                <% end %>
                                <% if @profile.plans.ad_archive? %><button type="button" id="archiveChange" data-ad="0" class="btn btn-white changeStatsDrop"> <i class="fa fa-cog"></i> Make Offline <span class="showtooltip" data-toggle="tooltip" data-placement="top" title="Change your advert status to hide it from search results. You must have a subscription level which allows you to archive adverts"><i class="fa fa-question-circle"></i></span></button><% end %>
                            </div>
                            <strong>You have <%= @classAds.size %> Adverts.</strong>
                        </div>

                    </div>
                    <% if !@classAds.nil? %>
                      <div class="table-responsive">
                        <table class="table table-hover issue-tracker">
                            <tbody>
                            <% @classAds.each do |ad| %>
                              <tr>
                                  <td>
                                    <div class="i-checks ad-list-actions" data-adnum="<%= ad.id %>"><label> <input type="radio" name="ad" value=""> <i></i></label></div>
                                  </td>
                                  <td>
                                    <% if ad.status.to_f == 1 %>
                                      <span class="label label-primary">Live <span class="showtooltip" data-toggle="tooltip" data-placement="top" title="Your advert can be searched for"><i class="fa fa-question-circle"></i></span></span>
                                    <% elsif ad.status.to_f == 2 %>
                                      <span class="label label-success">Sold <span class="showtooltip" data-toggle="tooltip" data-placement="top" title="Your advert has been sold successfully. Congratulations!"><i class="fa fa-question-circle"></i></span></span>
                                    <% else %>
                                      <span class="label label-danger">Offline <span class="showtooltip" data-toggle="tooltip" data-placement="top" title="This advert cannot be found or viewed by customers"><i class="fa fa-question-circle"></i></span></span>
                                    <% end %>
                                  </td>
                                  <td class="issue-info">
                                      <%= link_to ad.adtitle, edit_classified_path(ad.id) %>
                                      <small>
                                          Advert #<%= ad.id%>
                                      </small>
                                  </td>
                                  <td>
                                      <%= ad.created_at.to_s(:short)  %>
                                  </td>
                                  <td>
                                      <%= number_to_currency(ad.price, precision: 2, unit: "£") %> 
                                  </td>
                                  <noscript>
                                      <td class="text-right">
                                        <%= link_to 'edit', edit_classified_path(ad.id), class: "btn btn-white btn-xs" %>
                                        <%= link_to 'remove', classified_path(ad.id), method: :delete, class: "btn btn-danger btn-xs", data: { confirm: 'Are you certain you want to delete this?' } %>
                                        <% if @profile.plans.ad_archive? %><button class="btn btn-warning btn-xs changeStatsDrop" data-num="<%= ad.id%>">Change Status</button><% end %>
                                    </td>
                                  </noscript>
                              </tr>
                            <% end %>
                            </tbody>
                        </table>
                      </div>
                    <% end %>
                </div>

              <% if !@classAds.nil? %>
                <%= paginate @classAds %>
              <% end %>

            </div>
        </div>
    </div>
</div>

<% content_for :javascript do %>

  <script type="text/javascript">

      $(document).ready(function(){

        <% if !params[:tour].blank? %>
            theTour();
        <% end %>
      });
  </script>

<% end %>

app/views/classifieds/soldInvoices.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="container">
        <h2>Sold Product Invoices</h2>
        <ol class="breadcrumb">
            <li>
                <li><%= link_to "Dashboard", dashboard_path %></li>
            </li>
            <li class="active">
                <strong>Sold Invoices</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content container animated fadeInRight">
    
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Sold Products Invoices</h5>
                    <p class="note"><small><strong>NOTE:</strong> this is for reference purposes only</small></p>
                </div>
                <div class="ibox-content">
                    <% if !@sold.nil? %>
                      <div class="table-responsive">
                        <table class="table table-hover issue-tracker">
                            <tbody>
                            <% @sold.each do |invoice| %>
                              <tr>
                                  <td>
                                    <% if invoice.refund %>
                                      <span class="label label-danger">Refunded</span>
                                    <% else %>
                                      <span class="label label-success">Paid</span>
                                    <% end %>
                                  </td>
                                  <td class="issue-info">
                                      <%= link_to invoice.adtitle, "/invoices/view/#{invoice.id}" %>
                                      <small>
                                          Advert #<%= invoice.id%>
                                      </small>
                                  </td>
                                  <td>
                                      <%= invoice.created_at.to_s(:short)  %>
                                  </td>
                                  <td>
                                      <%= number_to_currency(invoice.price, precision: 2, unit: "£") %> 
                                  </td>
                                  <td class="text-right">
                                    <%= link_to "/invoices/view/#{invoice.id}", class: "btn btn-white" do %>
										<i class="fa fa-eye"></i> View Invoice
                                    <% end %>
                                </td>
                              </tr>
                            <% end %>
                            </tbody>
                        </table>
                      </div>
                    <% end %>
                </div>

              <% if !@sold.nil? %>
                <%= paginate @sold %>
              <% end %>

            </div>
        </div>
    </div>
</div>

app/views/classifieds/viewInvoice.html.erb
<div class="row wrapper border-bottom white-bg page-heading"> 
    <div class="container">
        <h2>Sold Product Invoices</h2>
        <ol class="breadcrumb">
            <li>
                <li><%= link_to "Dashboard", dashboard_path %></li>
            </li>
            <li>
                <strong>Sold Invoices</strong>
            </li>
            <li class="active">
                <strong>Product #<%= @invoice.id %> Invoice</strong>
            </li>
        </ol>
    </div>
</div>
<div class="row">
<div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="ibox-content p-xl">
            <div class="row">
                <div class="col-sm-6">
                    <h5>Sold By:</h5>
                    <span><strong><%= @profile.name %></strong></span>
                    <address>
                        <%= @profile.golfclub %><br>
                        <% latLon = "#{@profile.latitude}, #{@profile.longitude}" %>
                        <% address = Geocoder.search(latLon).first %>
                        <%= address.city %><br/>
                        <% if !address.state.nil? %><%= address.state %><br/><% end %>
                        <%= address.postal_code %><br/>
                        <%= address.country %><br/><br/>
                        <abbr title="Phone">T:</abbr> <%= @profile.phone %>
                    </address>
                </div>

                <div class="col-sm-6 text-right">
                    <% if @invoice.refund %>
                      <span class="label label-lg label-danger">Refunded</span>
                    <% end %>
                    <h4>Sale No.</h4>
                    <h4 class="text-navy"><%= @invoice.id %>0</h4>
                    <h5>Bought By:</h5>
                    <span><strong><%= @charge['source']['name'] %></strong></span>
                    <address>
                        <%= @charge['source']['address_line1'] %><br/>
                        <% if !@charge['source']['address_line2'].blank?%> <%= @charge['source']['address_line2'] %><br/> <% end %>
                        <%= @charge['source']['address_city'] %><br/> 
                        <%= @charge['source']['address_state']%><br/>  
                        <%= @charge['source']['address_country']%><br/><br/>  
                        <abbr title="Phone">T:</abbr> <%= @profile.phone %>
                    </address>
                    <p>
                        <span><strong>Invoice Date:</strong> <%= @invoice.created_at %></span><br />
                    </p>
                </div>
            </div>

            <div class="table-responsive m-t">
                <table class="table invoice-table">
                    <thead>
                    <tr>
                        <th>Item List</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Fees</th>
                        <th>Total Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <div><strong><%= @invoice.adtitle %></strong></div>
                            <small><%= @invoice.description %></small>
                        </td>
                        <td>1</td>
                        <td><%= number_to_currency(@invoice.price, precision: 2, unit: "£") %> </td>
                        <td><%= number_to_currency((2/@invoice.price)*100, precision: 2, unit: "£") %> </td>
                        <td><%= number_to_currency(@invoice.price- ((2/@invoice.price)*100), precision: 2, unit: "£") %> </td>
                    </tr>

                    </tbody>
                </table>
            </div><!-- /table-responsive -->

            <table class="table invoice-total">
                <tbody>
                <tr>
                    <td><strong>Sub Total :</strong></td>
                    <td><%= number_to_currency(@invoice.price, precision: 2, unit: "£") %> </td>
                </tr>
                <tr>
                    <td><strong>FEES :</strong></td>
                    <td><%= number_to_currency((2/@invoice.price)*100, precision: 2, unit: "£") %></td>
                </tr>
                <tr>
                    <td><strong>TOTAL :</strong></td>
                    <td><%= number_to_currency(@invoice.price- ((2/@invoice.price)*100), precision: 2, unit: "£") %> </td>
                </tr>
                </tbody>
            </table>

            <div class="well m-t">
                <strong>Legal</strong>
                This is a proof of purchase for this item. The customer has the right to collect the item listed above from you upon providing significant proof identification <strong>or</strong> proof of purchase (e.g purchase receipt). You must provide the customer with the item listed above upon proof of purchase or proof of identification. Failure to do so will result in a forced refund to the customer and your account will be terminated with immediate effect.
            </div>
            <div class="row">
                <div class="col-lg-4 pull-right">
                    <div class="title-action">
                        <% if !@invoice.refund %>
                            <a href="#" target="_blank" id="issueRefund" data-id="<%= params[:id] %>" class="btn btn-danger"><i class="fa fa-credit-card"></i> Issue Refund </a>&nbsp;&nbsp;
                        <% end %>
                        <a href="#" onclick="window.print(); return false;" target="_blank" class="btn btn-primary pull-right"><i class="fa fa-print"></i> Print Invoice </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>