config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :classifieds
  devise_for :users, controllers: { registrations: "registrations", :omniauth_callbacks => "omniauth_callbacks"  }, path_names: { sign_up: ''}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#home'
  
   %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'my-profile', to: 'profiles#profileoverview'

  get 'dashboard', to: 'dashboard#index'

  get 'signup', to: 'pages#signup'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
    get 'logout', to: 'devise/sessions#destroy'
  end

  get 'search', to: 'search#search'
  get 'search/autocomplete', to: 'search#autocomplete'

  post 'classifieds/product/confirm', to: 'classifieds#confirmPurchase'

  get 'users/upgrade', to: 'subscription#upgrade'
  get 'users/subscribe/confirm', to: 'subscription#confirm'
  get 'users/subscribe/success', to: 'subscription#success'
  get 'users/subscribe/error', to: 'subscription#error'
  post 'users/subscribe/', to: 'subscription#subscribe'
  post 'classifieds/payment/confirmation/:id', to: 'classifieds#stripeProcess'
  get 'classifieds/addons/confirm', to: 'classifieds#addonConfirm'
  get 'profile/gallery', to: 'profiles#galleryOverview'
  get 'invoices', to: 'classifieds#soldInvoices'
  get 'invoices/view/:id', to: 'classifieds#viewInvoice'
  put 'invoices/refund/:id', to: 'classifieds#processRefund'
  get 'purchase/:id/thankyou', to: 'classifieds#thankyou'

  post 'classifieds/:id/addons', to: 'classifieds#processAddon'
  get 'update_cats', to: 'classifieds#update_cats',  :defaults => { :format => 'json' }
  get 'ebaygetitem', to: 'classifieds#getebayitem',  :defaults => { :format => 'json' }
  get 'gbgetitem', to: 'classifieds#getgbitem',  :defaults => { :format => 'json' }
  get 'changeArchive', to: 'classifieds#changeArchive', :defaults => { :format => 'json' }
  get 'smartSearch', to: 'search#ajaxSearch', :defaults => { :format => 'json' }
  post 'submithelp', to: 'application#create_groove_ticket', :defaults => { :format => 'json' }
  post 'addonCreditsProcess', to: 'classifieds#processAddonCredits'
  post 'getBlogPosts', to: 'pages#getBlogPost',  :defaults => { :format => 'json' }
  get 'profile/:userid/gallery/:imgid/delete', to: 'profiles#galleryImageDelete', :defaults => {:format => 'json'}
  post 'profile/:id/gallery/new', to: 'profiles#galleryImageUpload', :defaults => {:format => 'json'}
  delete 'classifieds/:id/images/:imgid', to: 'classifieds#extraImageDelete', :defaults => {:format => 'json'}
  post 'profile/:id/status', to: 'profiles#createNewStatus', :defaults => {:format => 'json'}
  delete 'profile/status/:statusid', to: 'profiles#deleteStatus', :defaults => {:format => 'json'}
  post 'users/:userid/subscribe/cardchange',  to: 'subscription#cardChange', :defaults => {:format => 'json'}
  post 'profiles/:id/contact', to: 'profiles#emailContact', :defaults => {:format => 'json'}

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="row footer">
	<section class="small-footer">
		<div class="container">
			<div class="col-xs-4">
				<p>&copy; <%= Time.now.year %> Pro Finder Golf. All rights reserved.</p>
			</div>
			<div class="col-s-5 pull-right">
				<nav>
					<ul>
						<li><a target="_blank" href="/policies/terms-of-service.pdf">Terms of Service</a></li>
						<li><a target="_blank" href="/policies/privacy-policy.pdf">Privacy Policy</a></li>
						<li><a target="_blank" href="/policies/cookies-policy.pdf">Cookie Policy</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</section>
</footer>

app/views/layouts/_topnavbar.html.erb
<% if (user_signed_in? and @profile.wizard.blank?) or !user_signed_in? %>
    <div class="row border-bottom white-bg thenavbar">
        <nav class="navbar navbar-default" role="navigation">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
                <button aria-controls="navbar" aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    <i class="fa fa-reorder"></i>
                </button>
            <%= link_to(root_path, class: "navbar-brand") do %>
                <%= image_tag "svgs/branding/logo.svg", height: "40" %>
            <% end %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="col-sm-3 col-md-3 search-bar <%= 'hide' if params[:controller].tr('^A-Za-z0-9', ' ') == 'search' %>">
                <form action="<%= search_path %>" role="search" class="navbar-form" method="get">
                    <div class="input-group">
                        <input class="form-control input-lg typeahead" name="q" placeholder="Search..." required="true" />
                    </div>
                </form>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <% if !user_signed_in? %><li><%= link_to "Search", search_path %></li><% end %>
                <% if user_signed_in? %><li><%= link_to "Dashboard", dashboard_path %></li><% end %> 
                <% if !user_signed_in? %><li><%= link_to "Sign In", new_user_session_path %></li><% end %>
                <% if user_signed_in? %>
                    <li id="advert-tab">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Adverts <small><i class="fa fa-chevron-down"></i></small></a>
                        <ul class="dropdown-menu dropdown-user" role="menu" aria-labelledby="dLabel">
                            <li><%= link_to "Manage Adverts", classifieds_path() %></li>
                            <li><%= link_to "Sold Invoices", invoices_path %></li>
                        </ul>
                    </li>
                <% end %>
                <% if user_signed_in? %>
                    <li id="profile-tab">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Profile <small><i class="fa fa-chevron-down"></i></small></a>
                        <ul class="dropdown-menu dropdown-user" role="menu" aria-labelledby="dLabel">
                            <li><%= link_to "Profile Overview", my_profile_path %></li>
                            <li><%= link_to "Profile Image Gallery", profile_gallery_path %></li>
                        </ul>
                        
                    </li>
                <% end %> 
                <% if user_signed_in? %>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <small><i class="fa fa-chevron-down"></i></small></a>
                        <ul class="dropdown-menu dropdown-user" role="menu" aria-labelledby="dLabel">
                            <li><%= link_to "Edit Account", edit_user_registration_path %></li>
                            <li><%= link_to "My Subscription", users_upgrade_path %></li>
                        </ul>
                    </li>
                <% end %> 
                <li id="tour-help">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Help <small><i class="fa fa-chevron-down"></i></small></a>
                    <ul class="dropdown-menu dropdown-user" role="menu" aria-labelledby="dLabel">
                        <li><a href="#" data-toggle="modal" data-target="#myModal5">Submit Help Ticket</a></li>
                        <li><a href="https://profindergolf.freshdesk.com/support/home" target="_blank">FAQ</a></li>
                    </ul>
                </li>
                <!--<% if user_signed_in? %><li><%= link_to "Upgrade", users_upgrade_path %></li><% end %>-->
                <% if user_signed_in? %><li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li><% end %> 
            </ul>
          </div><!-- /.navbar-collapse -->
        </nav>
    </div>

    <div class="modal inmodal fade" id="myModal5" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form id="feedback_form" novalidate="novalidate" accept-charset="UTF-8">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title">Let Us Help You</h4>
                        <small class="font-bold">Having problems using the app? Want to ask about something specific? Fill out the form below and we'll get back to you ASAP.</small>
                    </div>
                    <div class="modal-body">
                        <div id="loading" class="loading hide">
                            <!-- By Sam Herbert (@sherb), for everyone. More @ http://goo.gl/7AJzbL -->
                            <svg width="38" height="38" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg">
                                <defs>
                                    <linearGradient x1="8.042%" y1="0%" x2="65.682%" y2="23.865%" id="a">
                                        <stop stop-color="#228844" stop-opacity="0" offset="0%"/>
                                        <stop stop-color="#228844" stop-opacity=".631" offset="63.146%"/>
                                        <stop stop-color="#228844" offset="100%"/>
                                    </linearGradient>
                                </defs>
                                <g fill="none" fill-rule="evenodd">
                                    <g transform="translate(1 1)">
                                        <path d="M36 18c0-9.94-8.06-18-18-18" id="Oval-2" stroke="url(#a)" stroke-width="2">
                                            <animateTransform
                                                attributeName="transform"
                                                type="rotate"
                                                from="0 18 18"
                                                to="360 18 18"
                                                dur="0.9s"
                                                repeatCount="indefinite" />
                                        </path>
                                        <circle fill="#228844" cx="36" cy="18" r="1">
                                            <animateTransform
                                                attributeName="transform"
                                                type="rotate"
                                                from="0 18 18"
                                                to="360 18 18"
                                                dur="0.9s"
                                                repeatCount="indefinite" />
                                        </circle>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="text" name="name" value="<%= @profile.name if !@profile.nil? %>" placeholder="Your Full Name..." required="" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="email" type="email" name="email" value="<%= @profile.user.email if !@profile.nil? %>" placeholder="Your Email Address..."  required="" />
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="text" name="subject" placeholder="What's your issue about?" required="" />
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="message" placeholder="Tell us what's on your mind..." required="" ></textarea>
                        </div>
                    </div>  

                    <div class="modal-footer">
                        <button type="cancel" class="btn btn-white" data-dismiss="modal">Close</button>
                        <button type="submit" id="helpSubmit" class="btn btn-primary ladda-button" data-style="slide-up"><span class="ladda-label">Save changes</span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pro Finder Golf</title>
  	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "print", media: "print" %>
    <link href='https://api.tiles.mapbox.com/mapbox.js/v2.2.3/mapbox.css' rel='stylesheet' />
  	<%= csrf_meta_tags %>
  </head>
  <body class="top-navigation">

      <!-- Wrapper-->
      <div id="wrapper" class="<%= params[:controller].tr('^A-Za-z0-9', ' ') %> <%= params[:action] %>">

          <!-- Page wraper -->
          <div id="page-wrapper" class="gray-bg <%= @extra_class %>">
              <!-- Page wrapper -->
              <% if params[:controller].downcase().include? "pages" or params[:controller].downcase().include? "devise" %>

                <%= render 'layouts/topnavbar' %>

                <!-- Main view  -->

                  <%= render partial: "layouts/flash_messages", flash: flash %> 
      
                  <%= yield %>
      
              <% else %>
              
                  <div class="propanel">
                    <%= render 'layouts/topnavbar' %>
                  </div>

                  <%= render partial: "layouts/flash_messages", flash: flash %> 
      
                  <%= yield %>

              <% end %>

              <!-- Footer -->
              <%= render 'layouts/footer' %>

          </div>
          <!-- End page wrapper-->

      </div>
      <!-- End wrapper-->
      
      <script src='https://api.tiles.mapbox.com/mapbox.js/v2.2.3/mapbox.js'></script>

      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

      <script type="text/javascript" id="cookiebanner" data-moreinfo="/policies/cookies-policy.pdf" data-bg="#228844" src="<%= asset_path( "cookiebanner.js") %>"></script>
      
      <% if Rails.env == "production"  %>

        <% content_for :javascript do %>
          <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-73085092-1', 'auto');
            ga('send', 'pageview');

          </script>
          <!-- Hotjar Tracking Code for https://www.profinder.golf -->
          <script>
              (function(h,o,t,j,a,r){
                  h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
                  h._hjSettings={hjid:174359,hjsv:5};
                  a=o.getElementsByTagName('head')[0];
                  r=o.createElement('script');r.async=1;
                  r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                  a.appendChild(r);
              })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
          </script>

          <script> 
            var $buoop = {vs:{i:9,f:25,o:12.1,s:7},c:2}; 
            function $buo_f(){ 
             var e = document.createElement("script"); 
             e.src = "//browser-update.org/update.min.js"; 
             document.body.appendChild(e);
            };
            try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
            catch(e){window.attachEvent("onload", $buo_f)}
          </script> 
  
        <% end %>
      <% end %>

      <%= yield :javascript %>

  </body>
</html>